### ISSUE TITLE
disable shuffle for one Gallery...

### ISSUE THREAD

**Issue by cnichte** [bep/gallerydeluxe#34]
This in more for more than one gallery -  galleries deluxe. You can only set this for all galleries:

```toml
[params]
    [params.gallerydeluxe]
        shuffle     = true
        reverse     = true
        enable_exif = false
```

It would be cool if you could set the global settings individually for each gallery. 

Perhaps via Frontmatter like so:

```md
---
title: A Gallery
categories: [Cat1, Cat2]
date: 2019-01-01
params:
  gallery_shuffle: true
  gallery_reverse: true
  gallery_enable_exif: false
---
Description
```

Best regards - Carsten
